version: '3.8'

services:
  fontend: 
    image: fontend
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/project
      - /project/node_modules
    environment:
      - NODE_ENV=production
